"""empty message

Revision ID: 1b579f4eef0c
Revises: 053b08947c70
Create Date: 2023-05-01 14:07:09.649862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b579f4eef0c'
down_revision = '053b08947c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('none_col', sa.Integer(), nullable=True))
        op.execute(
            '''
                update messages
                set sender_id = sup_sender_id;
            '''
        )
        op.execute(
            '''
                update messages
                set receiver_id = sup_receiver_id;
            '''
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('none_col')
        op.execute(
            '''
                update messages
                set sup_sender_id = sender_id;
            '''
        )
        op.execute(
            '''
                update messages
                set sup_receiver_id = receiver_id;
            '''
        )
    # ### end Alembic commands ###
