"""empty message

Revision ID: 5dd2efc25e47
Revises: 00207f3ed67d
Create Date: 2023-05-01 13:58:50.198832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd2efc25e47'
down_revision = '00207f3ed67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sup_sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sup_receiver_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('sup_receiver_id')
        batch_op.drop_column('sup_sender_id')

    # ### end Alembic commands ###
