"""empty message

Revision ID: 813457f02584
Revises: a5b5b8c2a682
Create Date: 2023-04-12 16:58:02.727535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813457f02584'
down_revision = 'a5b5b8c2a682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
